version: 0.2

env:
  variables:
    JAVA_HOME: "/usr"
   

phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y maven
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install --fail-never
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
