version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.141.x86_64"

phases:
  install:
    commands:
      - yum update -y
      - yum install -y maven
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
